export const data = [
    {   
        id: 1,
        title: 'Mother', 
        genre: 'Indie Pop', 
        artist: 'Matt Maltese', 
        link: 'https://open.spotify.com/track/1inhG9jVy0SojA6OZogtlv?si=6d6cf463963845e9'
    },
    {
        id: 2, 
        title: 'Money', 
        genre: 'Rock', 
        artist: 'Lime Cordiale',
        link: 'https://open.spotify.com/track/2Vi8BQIM9vCQkkrvf3VPjI?si=84875b44eddb4cdf',
    }, 
    {
        id: 3, 
        title: 'I Know You', 
        genre: 'Indie Pop', 
        artist: 'Faye Webster',
        link: 'https://open.spotify.com/track/71BWZa1liIRyUiuJ3MB66o?si=9c6c80b44fa14420',
    }, 
    {
        id: 4, 
        title: 'Circle the Drain', 
        genre: 'Indie Pop', 
        artist: 'Soccer Mommy',
        link: 'https://open.spotify.com/track/2drtd6SptpMJ1KylMQ7mrE?si=bb269cbc89674e88',
    }, 
    {
        id: 5, 
        title: 'Be My Angel', 
        genre: 'Alternative', 
        artist: 'Mazzy Star',
        link: 'https://open.spotify.com/track/3R6kyOmqWcAsqZqqe9CGL0?si=fcd3806e1de54513',
    }, 
    {
        id: 6, 
        title: 'Come Away With Me', 
        genre: 'Indie Rock', 
        artist: 'Norah Jones',
        link: 'https://open.spotify.com/track/6jGnykaS6TkWp15utXSAeI?si=29132dded1254647',
    }, 
    {
        id: 7, 
        title: 'Poster Girl', 
        genre: 'Rock', 
        artist: 'MOGY',
        link: 'https://open.spotify.com/track/0dxhQ2yxYrqSfPzQ6Q1fG8?si=310a14a6c9314e6d',
    }, 
    {
        id: 8, 
        title: 'Poly Blue', 
        genre: 'Folk', 
        artist: 'Jessica Pratt',
        link: 'https://open.spotify.com/track/70WayNC8zTjyTQkL6jtoTS?si=7ab707d41cd848a5',
    },
    {
        id: 9, 
        title: "Pretty isn't Pretty",
        genre: 'Pop', 
        artist: 'Olivia Rodrigo',
        link: 'https://open.spotify.com/track/6W9l02gRsXVxzIuQC1oc1X?si=91482323cd034a4b', 
    },
    {
        id: 10, 
        title: "In the Waiting Room",
        genre: 'Alternative', 
        artist: 'A Country Western', 
        link: 'https://open.spotify.com/track/6s7LGOXuJbfEBn3ILPiZbM?si=fe6fd1fd95a04947',
    }, 
    {
        id: 11, 
        title: 'Being Around',
        genre: 'Alternative',  
        artist: 'The Slaps',
        link: 'https://open.spotify.com/track/2kIuv81AVVFkFQyfR605q6?si=a62c04aa05074cc5',
    }, 
    {
        id: 12, 
        title: 'Socks',  
        genre: 'Pop', 
        artist: 'Dominic Fike', 
        link: 'https://open.spotify.com/track/05fTCmfInpZXpb5Xn1GKGs?si=6dfa32d6280345bc',
    }, 
    {
        id: 13, 
        title: 'The Start of Something', 
        genre: 'Indie Pop', 
        artist: 'Voxtrot',
        link:'https://open.spotify.com/track/30fQvBnDR8jLdN0SFcsFos?si=8aa6fe6d1f26448b', 
    }, 
    {
        id: 14, 
        title: 'Photograph', 
        genre: 'Indie Rock', 
        artist: 'Arcade Fire', 
        link: 'https://open.spotify.com/track/5Sj3F1OEvSz52ehpxTJZlR?si=f990769e0ddf4b10',
    }, 
    {
        id: 15, 
        title: 'CHANCES', 
        genre: 'Electronic', 
        artist: 'KAYTRANADA', 
        link: 'https://open.spotify.com/track/439X8jGytErRiPnaoUJHju?si=4310fed7057c457c', 
    },
    {
        id: 16, 
        title: 'Prom Queen', 
        genre: 'Indie Pop', 
        artist: 'Beach Bunny',
        link: 'https://open.spotify.com/track/6MpCaSIOfqBqbMED4kXgNY?si=4da8c19c972141c9', 
    },
    {
        id: 17, 
        title: 'Kids', 
        genre: 'Indie Rock', 
        artist: 'Current Joys', 
        link: 'https://open.spotify.com/track/3pyyGVqWvRMq43qtJBzxe0?si=27e8138edb97447d', 

    }, 
    {
        id: 18, 
        title: 'My Song', 
        genre: 'Folk', 
        artist: 'Labi Siffre', 
        link: 'https://open.spotify.com/track/2EQWbkcNoKPOXQtJM7nqRV?si=03fd302d806f4a98', 
    },
    {
        id: 19,
        title: 'Kyrstal', 
        genre: 'Indie Pop', 
        artist: 'Matt Maltese', 
        link: 'https://open.spotify.com/track/5JJPfHpByZ66XsEyCNVi2p?si=38d625820a5a410f', 
    }, 
    {
        id: 20, 
        title: 'Bonehead', 
        genre: 'Alternative', 
        artist: 'Harry Permezel',
        link: 'https://open.spotify.com/track/3XQefG57kqvTaqfmg1cu0S?si=208d820386f24884',
    },
    {
        id: 21, 
        title: 'Down the Line', 
        genre: 'Indie Rock', 
        artist: 'Beach Fossils', 
        link: 'https://open.spotify.com/track/05ZUxHiGT7VR6ShJjhwJxn?si=c77e8593b3dd4bb6', 
    },
    {
        id: 22, 
        title: 'Flowers in December', 
        genre: 'Alternative', 
        artist: 'Mazzy Star', 
        link: 'https://open.spotify.com/track/0G6Ws8Gbdt0S7pZeuYmkmm?si=9fc2ee5e65b9477b', 
    },
    {
        id: 23, 
        title: "Boys Don't Cry", 
        genre: 'Rock', 
        artist: 'The Cure', 
        link: 'https://open.spotify.com/track/2RKDbMwtJgKc76H9oPo7Cl?si=e19ac9e5578a49ed', 
    },
    {
        id: 24, 
        title: 'Ooh La', 
        genre: 'Indie Rock', 
        artist: 'The Kooks', 
        link: 'https://open.spotify.com/track/6xqCTPxYnRf8X0p6N5Vw2T?si=59ae39ac2feb4d83', 
    },
    {
        id: 25, 
        title: 'Duke', 
        genre: 'Alternative', 
        artist: 'Cate Le Bon', 
        link: 'https://open.spotify.com/track/0arC3c7CaQHgRQb9z6zFa1?si=95f9ba9a33d2433b', 
    },
    {
        id: 26, 
        title: 'For No One', 
        genre: 'Rock', 
        artist: 'The Beatles', 
        link: 'https://open.spotify.com/track/1kDkaFlmkdEZiVUogaP9OZ?si=df119f62887b4c84', 
    },
    {
        id: 27, 
        title: 'Positively 4th Street', 
        genre: 'Rock', 
        artist: 'Bob Dylan', 
        link: 'https://open.spotify.com/track/6q9rNSvE59IVT3ZlEorvYb?si=9009c0868a084b88', 
    },
    {
        id: 28, 
        title: "You Know I'm Dowwn", 
        genre: 'Indie Pop', 
        artist: 'Frog', 
        link: 'https://open.spotify.com/track/1yVyCAFIVeqT7ytG271idT?si=e6a6204b0099479a', 
    },
    {
        id: 29, 
        title: 'Mary', 
        genre: 'Indie Pop', 
        artist: 'Alex G', 
        link:'https://open.spotify.com/track/4p9iQNEmsIGkB6eG8Val8n?si=ce440dbbae4c4114'
    },
    {
        id: 30, 
        title: 'I Won!', 
        genre: 'Alternative', 
        artist: 'Sipper', 
        link: 'https://open.spotify.com/track/3KQDLIK3HZkPJg7HS0d7jx?si=f82ab636288a4e0e', 
    }
]